name: Deploy to FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Ferozo FTP
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: sd-1941427-h00034.ferozo.net
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/mirestoapp/
        local-dir: ./public_html/mirestoapp/
        dangerous-clean-slate: false
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .vscode/**
        log-level: verbose
        timeout: 60000
